### ISSUE TITLE
Crash after waves

### ISSUE THREAD

**Issue by krasiooo** [gtteamamxx/Tower-Defense#17]
The server is getting crashed in 14-15 wave or high.

**Comment by gtteamamxx** [comment]
Can you explain in detail what's happening?
I know there were a crash sometimes, but i played sometimes ago many times and it didnt happen to me

https://www.youtube.com/watch?feature=player_embedded&v=O-lF6o7ajxc

I can't now work on this mod, so fix will not come in nearest time.

You can check branch Tower defense v2, i was rewriting this mod with new featuers, like monsters throwing stones to players etc.

Thanks for an issue

**Comment by krasiooo** [comment]
V2 version didn't work for me. I have to combine the v1 and v2?

**Comment by gtteamamxx** [comment]
V2 is not finished yer




Pobierz aplikację Outlook dla systemu Android







On Sat, Mar 2, 2019 at 5:49 PM +0100, "krasiooo" <notifications@github.com> wrote:












V2 version didn't work for me.

**Comment by krasiooo** [comment]
When will be finished, because the v1 have crashes.

**Comment by gtteamamxx** [comment]
Idk, im not actuakky working ok this mod. 




Pobierz aplikację Outlook dla systemu Android







On Sat, Mar 2, 2019 at 6:49 PM +0100, "krasiooo" <notifications@github.com> wrote:












When will be finished, because the v1 have crashes.
