### ISSUE TITLE
Why can't I compile some SMAs[Help]

### ISSUE THREAD

**Issue by cssaigao** [gtteamamxx/Tower-Defense#18]
My Idol
When I compile part of SMA, there will be some errors.
So I have some questions.
1. This plugin uses AMXMODX v?
2. Do you have a complete Inc / Full HLDS / compiler (if you have this, can you send it to me)
3. If you can't do 2, I hope you can teach me how to install plugins.
Please...

**Comment by gtteamamxx** [comment]
Hello there

yep, this plugin uses amxmodx
i don't have at the moment neccesry files to build that mod.

If you want to play it, you have to build it loccaly. 
Download compiler from amxmodx site (1.8.3) .

**Comment by cssaigao** [comment]
> Hello there
> 
> yep, this plugin uses amxmodx
> i don't have at the moment neccesry files to build that mod.
> 
> If you want to play it, you have to build it loccaly.
> Download compiler from amxmodx site (1.8.3) .

Wow!!
I solved it!!
Thanks,My idol !!!!
