### ISSUE TITLE
Brakujące pliki .sma od klas

### ISSUE THREAD

**Issue by AdrianJagodznski** [gtteamamxx/Tower-Defense#19]
Cześć,
czy możecie podesłać brakujące .sma plików 

;td_class_engineer.amxx			; Engineer
;td_class_sniper.amxx			; Sniper
;td_class_sprinter.amxx			; Sprinter
;td_sprite_turret_ammo.amxx	;	Epic sprites
;td_sprite_engine.amxx			; main engine for sprite (by DarkGL & optymalized by GT Team)

Byłbym bardzo wdzięczny

**Comment by gtteamamxx** [comment]
Hej, te rzeczy są w starszej wersji
0.5 chyba

https://github.com/gtteamamxx/Tower-Defense/tree/b4455f616f1bd312743ac78be5ca6f952a780407/addons/amxmodx/scripting

**Comment by AdrianJagodznski** [comment]
Dzięki za szybką odpowiedź, nie znalazłem nowszych wersji, nie ogarnąłem jak znaleźć.
Teraz zaś mam problem tylko z 1 pluginem 
`L 05/05/2020 - 10:41:39: [AMXX] Plugin "td_vip.amxx" failed to load: Plugin uses an unknown function (name "td_get_vip_model") - check your modules.ini.`

**Comment by gtteamamxx** [comment]
Używasz pliku td_vip z wersji 0.5, która nie jest wspierana w najnowszej wersji.
VIP jest już built-in w wersji 1.1 (najnowszy branch master)

Więc jak chcesz rzeczy z 0.5 uzywac w 1.1 to Ci to nie zadziała
![image](https://user-images.githubusercontent.com/10392319/81057039-f77ea980-8ecb-11ea-8faa-28fb39465eaf.png)

**Comment by AdrianJagodznski** [comment]
Po wrzuceniu wersji 1.1 na serwer nie działają klasy
( 46) Load fails: Plugin uses an unknown function (name "td_register_class") - check your modules.ini.
( 47) Load fails: Plugin uses an unknown function (name "td_register_class") - check your modules.ini.
I nie ma języka PL - w wersji 0.5 był

**Comment by AdrianJagodznski** [comment]
Mam rozumieć, że wrzucając 0,5 będę miał VIP, Klasy i Polski język
A na wersji 1.1 już tego nie uświadczę?

**Comment by gtteamamxx** [comment]
Nope. 

1. Nie ma klas na 1.1, więc te pluginy Ci tam nie pójdą
2. Na 1.1 są tylko umiejętności nabywane wraz z expem
3. 0.5 ma dużo błędów i nie polecalbym korzystania z tej wersji.
4. Niestety nie ma wersji PL na 1.1. Jest to zrobione w celi optymalizacji. Musiałyś sobie każdy plik przetłumaczyć ręcznie.
5. VIP jest na 0.5 w osobnym pluginie, na 1.1 jest już wbudowany w silnik (są cvary do tego)

**Comment by AdrianJagodznski** [comment]
Super dzięki za wyjaśnienie. :)

**Comment by gtteamamxx** [comment]
Luzik :)
