### ISSUE TITLE
Problem z wczytywaniem modeli granatów

### ISSUE THREAD

**Issue by AdrianJagodznski** [gtteamamxx/Tower-Defense#20]
Hej, jeszcze jedna mała sprawa.
Nie wiem dlaczego, ale nie wczytuje mi od początku modeli granatów.
Sprawdziłem pliki konfiguracyjne i są zdefiniowane prawidłowo jak były oraz są wrzucone na ftp.

Problem dotyczy tylko
`L 05/06/2020 - 09:12:35: DEBUG: Loading model 'FLAME_GRENADE_MDL_V' | set 'v_burngrenade' or ''
L 05/06/2020 - 09:12:35: DEBUG: Defined model 'models/TD/.mdl' nie odnaleziono.
L 05/06/2020 - 09:12:35: DEBUG: Loading model 'FLAME_GRENADE_MDL_W' | set 'w_burngrenade' or ''
L 05/06/2020 - 09:12:35: DEBUG: Defined model 'models/TD/.mdl' nie odnaleziono.
L 05/06/2020 - 09:12:35: DEBUG: Loading model 'FLAME_GRENADE_MDL_P' | set 'p_burngrenade' or ''
L 05/06/2020 - 09:12:35: DEBUG: Defined model 'models/TD/.mdl' nie odnaleziono.
L 05/06/2020 - 09:12:35: DEBUG: Loading model 'FROZEN_GRENADE_MDL_V' | set 'v_frozengrenade' or ''
L 05/06/2020 - 09:12:35: DEBUG: Defined model 'models/TD/.mdl' nie odnaleziono.
L 05/06/2020 - 09:12:35: DEBUG: Loading model 'FROZEN_GRENADE_MDL_W' | set 'w_frozengrenade' or ''
L 05/06/2020 - 09:12:35: DEBUG: Defined model 'models/TD/.mdl' nie odnaleziono.
L 05/06/2020 - 09:12:35: DEBUG: Loading model 'FROZEN_GRENADE_MDL_P' | set 'p_frozengrenade' or ''
L 05/06/2020 - 09:12:35: DEBUG: Defined model 'models/TD/.mdl' nie odnaleziono.
L 05/06/2020 - 09:12:35: DEBUG: Loading model 'STOP_GRENADE_MDL_V' | set 'v_stopgrenade' or ''
L 05/06/2020 - 09:12:35: DEBUG: Defined model 'models/TD/.mdl' nie odnaleziono.
L 05/06/2020 - 09:12:35: DEBUG: Loading model 'STOP_GRENADE_MDL_W' | set 'w_stopgrenade' or ''
L 05/06/2020 - 09:12:35: DEBUG: Defined model 'models/TD/.mdl' nie odnaleziono.
L 05/06/2020 - 09:12:35: DEBUG: Loading model 'STOP_GRENADE_MDL_P' | set 'p_stopgrenade' or ''
L 05/06/2020 - 09:12:35: DEBUG: Defined model 'models/TD/.mdl' nie odnaleziono.
L 05/06/2020 - 09:12:35: DEBUG: Loading model 'VIP_MODEL' | set 'vip' or ''
L 05/06/2020 - 09:12:35: DEBUG: Defined player model 'models/player//.mdl' nie odnaleziono.
L 05/06/2020 - 09:12:35: DEBUG: Loading models finished.`

Reszta wczytuje się prawidłowo

**Comment by gtteamamxx** [comment]
Hej. Wrzucilem sobie wszystko u siebie lokalnie i mod od razu mi zadziałał. Pokaż konfigurację td_models.cfg

**Comment by AdrianJagodznski** [comment]
Mój plik https://megawrzuta.pl/download/dc2f4a75b5947d018b008b7f8b86a410.html
Plik jest domyślny nic w nim nie zmieniałem.
Dodatkowo jak widzisz wszystko jest na ftp https://prnt.sc/sbqmjl
Mod nie zaczytuje tylko granatów.

**Comment by gtteamamxx** [comment]
Hej. Tutaj jest bug w logowaniu, natomiast pliki wczytywane są poprawnie.
Log mówi, że probuje ustawić: `Problem dotyczy tylko
L 05/06/2020 - 09:12:35: DEBUG: Loading model 'FLAME_GRENADE_MDL_V' | set 'v_burngrenade' or ''

'v_burngrenade' - to co jest w configu, lub następną wartość, czyli ''.

W kodzie logowanie wygląda w taki sposób. Na czerwono zaznaczyłem wartość tablicy wypisującą `v_burngrenade`:
![image](https://user-images.githubusercontent.com/10392319/81155532-55bb9300-8f85-11ea-8799-235ab7c1b7e1.png)

Zwróc uwage, że jest to `szTemp[2]`.

W przypadku ustawiania wartości do już właściwych zmiennych wygląda to w taki sposób. Zwróć uwage, na czerwoną czerwony prostokąt. Też jest `szTemp[2]`.

![image](https://user-images.githubusercontent.com/10392319/81155680-7daaf680-8f85-11ea-9899-3e7296d03b27.png)

Wczytywanie konfiguracji jest okej, po prostu wypisuje głupoty w konsoli akurat. Taki drobny bug.
BTW. Gdyby mod nie był w stanie wczytac modeli serwer by nie wstał, bo nie mógłby "sprecachować" modeli "models/TD/.mdl"

Poszukałbym problemu gdzie indziej w tej kwesti co do granatów. 
Odpaliłem jeszcze raz CS'a i modele mi się podmieniają.

Przesyłam zrzut z gameplaya, który był grany na dokładnie tej samej wersji jaka tu się znajduję.
Granat kupiony, model podmieniony.

![image](https://user-images.githubusercontent.com/10392319/81156223-032ea680-8f86-11ea-9cb9-ec709e3d38f1.png)

**Comment by AdrianJagodznski** [comment]
Super dzięki za podpowiedź, prześledzę dziś jeszcze czy nie ma jakichś ewentualnych rzeczy do poprawy.
Niedługo postaram się podesłać przetłumaczone wszystkie pluginy na PL.
