### ISSUE TITLE
no precache: models/TD/.mdl

### ISSUE THREAD

**Issue by AdrianJagodznski** [gtteamamxx/Tower-Defense#21]
Tak jak pisaliśmy wcześniej jednak jest coś nie tak z wczytywaniem modeli.
Crashuje serwer przy pierwszej fali i wyrzuca w konsoli 
ERROR : Host_Error: PF_setmodel_I: no precache: models/TD/.mdl

**Comment by gtteamamxx** [comment]
Hej, niestety nie jestem w stanie tego odwzorować.
Są serwery postawione z tym modem, więc skoro im działa, mnie również, to musi być coś u Ciebie nie tak :|
