### ISSUE TITLE
create a new config for new maps

### ISSUE THREAD

**Issue by talibanaa** [gtteamamxx/Tower-Defense#24]
Hello again, can you tell me how to create new zones for new maps, because when i am use default settings like from your config file, its not working, a need few new zones for start game and vote for specific maps like

td_night_remake
td_empire_remake
td_sherwood_caste
td_village
td_desert_base
td_dark_night
td_dust_delta
td_circulation

For example, if I use the same settings on a map like td_night  similar to it like td_night_remake, I do not see any area in the 
game for start or vote.

How to find coordinates ??? THANKS

**Comment by gtteamamxx** [comment]
Hi.

Every map has diffrent coordinates. 
When you are on map and you are an admin, you have access to ADMIN menu (say /menu), from where you can read START ZONE coordinates in console and save to new config file.

**Comment by talibanaa** [comment]
Thank you!

На нд, 31.10.2021 г. в 19:43 ч. GT Team ***@***.***> написа:
